language: node_js
node_js:
  - 'node'
cache:
  directories:
    - 'node_modules'
  yarn: true
install:
  - yarn
scripts:
  - yarn build
  - yarn test
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: ''
